version: '3.7'

services:
    app:
        build:
            context: .
        ports: 
            - "5000:5000"
        volumes: 
            - ../DockerTestProject:/app
        command: sh -c "python manage.py runserver 0.0.0.0:5000"
        environment: 
